default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  rpharma_url: "https://rinpharma.com/"
  rpharma_logo: "http://rinpharma.com/media/logo_hu7da996d8ce7178f65929875a2132de7e_457633_0x70_resize_lanczos_2.png"